FROM alpine:latest
LABEL maintainer="ManishK_ <manish.khadka@nepallink.net>

RUN apk update
RUN apk add bash build-base wget pkgconfig tar --no-cache

#Add user www required by php-fpm
RUN adduser -D -s /sbin/nologin www

#Install necessary packages
RUN apk add sqlite sqlite-dev sqlite-libs openssl openssl-dev openssl-dbg libxml2 libxml2-dev  \
    libxml2-dbg libcurl curl-dev libpng libpng-dev libpng-static libpng-doc libpng-utils  \
    libjpeg-turbo libjpeg-turbo-utils libjpeg-turbo-doc libjpeg libjpeg-turbo-dev freetype freetype  \
    freetype-dev freetype-doc freetype-static oniguruma oniguruma-dev libzip libzip-doc libzip-dev libzip-tools  \
    gettext-dev #gettext-dev package is to remove `libinitl.h` file not found issue.

#Downloading PHP7.4 beta version 2 and install
RUN wget -c -O php7.4.tar.gz "https://downloads.php.net/~derick/php-7.4.0beta2.tar.gz" && \
    tar -zxvf php7.4.tar.gz && \
    rm -rvf php7.4.tar.gz && \
    cd php-7.4.0beta2 && \
    echo -e \e[32m"Installation begins now" && \
    echo -e "\e[39m" && \
    ./configure --prefix=/usr/local/php \
    --with-config-file-path=/usr/local/php/etc \
    --with-config-file-scan-dir=/usr/local/php/etc/php.d \
    --with-fpm-user=www \
    --with-fpm-group=www \
    --with-mysqli \
    --with-pdo-mysql \
    --with-openssl \
    --enable-gd \
    --with-iconv \
    --with-zlib \
    --with-gettext \
    --with-curl \
    --with-jpeg \
    --with-freetype \
    --enable-fpm \
    --enable-xml \
    --enable-inline-optimization \
    --enable-mbregex \
    --enable-mbstring \
    --enable-mysqlnd \
    --enable-sockets \
    --with-zip \
    --enable-soap \
    --enable-bcmath \
    --enable-exif \
    --enable-pcntl \
    --disable-cgi \
    --disable-phpdbg \
    && \
    make -j4 > /dev/null && make install;

RUN cd / && \
    cp ./php-7.4.0beta2/php.ini-production /usr/local/php/etc/php.ini && \
    mv /usr/local/php/etc/php-fpm.conf.default /usr/local/php/etc/php-fpm.conf && \
    mv /usr/local/php/etc/php-fpm.d/www.conf.default /usr/local/php/etc/php-fpm.d/www.conf  && \
    strip /usr/local/php/bin/php && \
    strip /usr/local/php/sbin/php-fpm 

RUN ln -s /usr/local/php/sbin/php-fpm /usr/local/bin/php-fpm && \
    ln -s /usr/local/php/bin/php /usr/local/bin/php && \
    ln -s /usr/local/php/bin/phpize /usr/local/bin/phpize && \
    ln -s /usr/local/php/bin/pecl /usr/local/bin/pecl && \
    ln -s /usr/local/php/bin/php-config /usr/local/bin/php-config

WORKDIR /usr/local/php/etc/php-fpm.d/
COPY ./DockerConfig/php/www.conf .

WORKDIR /home/nepallink/public_html
COPY . .
